### ISSUE TITLE
Fails to build with Go 1.25

### ISSUE THREAD

**Issue by stefanb** [mark3labs/mcphost#121]
👋  When trying to build it with Go 1.25 (rc3) in
* https://github.com/Homebrew/homebrew-core/pull/226636

The build [failed](https://github.com/Homebrew/homebrew-core/actions/runs/16788155185/job/47549802968?pr=226636#step:3:18792) with:
```
  # github.com/bytedance/sonic/internal/rt
  /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/bytedance/sonic@v1.13.3/internal/rt/stubs.go:33:22: undefined: GoMapIterator
  /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/bytedance/sonic@v1.13.3/internal/rt/stubs.go:36:54: undefined: GoMapIterator
```

Mcphost is still using
https://github.com/mark3labs/mcphost/blob/d3f9759eb4cacf8da2cd4d0526414630ad146655/go.mod#L10

This should be upgraded to [1.14.0](https://github.com/bytedance/sonic/releases/tag/v1.14.0) (or later) to get upstream fix:
* https://github.com/bytedance/sonic/pull/808

Please note, that Go 1.25 is scheduled for release in August.

**Comment by stefanb** [comment]
Fix proposed in
* https://github.com/mark3labs/mcphost/pull/122
