### ISSUE TITLE
Does not compile with Ollama 0.9

### ISSUE THREAD

**Issue by AlekSi** [mark3labs/mcphost#57]
Ollama version before 0.9 had a security problem: https://pkg.go.dev/vuln/GO-2025-3695
But mcphost does not compile with that version due to incompatible types:

[...]/pkg/mod/github.com/mark3labs/mcphost@v0.8.0/pkg/llm/ollama/provider.go:156:17: cannot use struct{Type string `json:"type"`; Required []string `json:"required"`; Properties map[string]struct{Type string `json:"type"`; Description string `json:"description"`; Enum []string `json:"enum,omitempty"`} `json:"properties"`}{…} (value of type struct{Type string "json:\"type\""; Required []string "json:\"required\""; Properties map[string]struct{Type string "json:\"type\""; Description string "json:\"description\""; Enum []string "json:\"enum,omitempty\""} "json:\"properties\""}) as struct{Type string "json:\"type\""; Defs any "json:\"$defs,omitempty\""; Items any "json:\"items,omitempty\""; Required []string "json:\"required\""; Properties map[string]struct{Type api.PropertyType "json:\"type\""; Items any "json:\"items,omitempty\""; Description string "json:\"description\""; Enum []any "json:\"enum,omitempty\""} "json:\"properties\""} value in struct literal

**Comment by AlekSi** [comment]
I beleive this is still the problem
